# Generated by Django 4.1.2 on 2022-10-13 14:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('cuisines', models.CharField(max_length=100, null=True)),
                ('reserve', models.CharField(max_length=100, null=True)),
                ('rating', models.IntegerField(blank=True)),
                ('price', models.FloatField()),
                ('review', models.TextField(max_length=500, null=True)),
                ('featured_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
