# Generated by Django 4.1.2 on 2022-10-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_review_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='restaurants',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
    ]
