# Generated by Django 4.1.2 on 2022-10-19 12:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_restaurant_cuisines_remove_restaurant_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
