# Generated by Django 4.1.2 on 2022-10-29 06:41

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_alter_review_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('number_of_guests', models.IntegerField()),
                ('table_number', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('additional_info', models.CharField(max_length=250, null=True)),
                ('restaurants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
