# Generated by Django 4.1.2 on 2022-11-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
