# Generated by Django 4.1.2 on 2022-11-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date']},
        ),
    ]
