# Generated by Django 4.1.2 on 2022-11-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_alter_menu_created_on_alter_menu_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='updated_on',
        ),
    ]
