# Generated by Django 4.1.2 on 2022-11-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_alter_reservation_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='cuisine_image',
            new_name='menu_image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='cuisine',
        ),
    ]
