# Generated by Django 4.1.2 on 2022-11-02 23:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_rename_cuisine_image_menu_menu_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'African'), (2, 'Chinese'), (3, 'Asian'), (4, 'Irish'), (5, 'Continental')], max_length=11, null=True),
        ),
    ]
