# Generated by Django 4.1.2 on 2022-11-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_alter_reservation_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
