# Generated by Django 4.1.2 on 2022-11-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0022_restaurant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.PositiveSmallIntegerField(choices=[(1, 'African'), (2, 'Chinese'), (3, 'Asian'), (4, 'Irish'), (5, 'Continental')], null=True),
        ),
    ]
