# Generated by Django 4.1.2 on 2022-11-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0023_alter_restaurant_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='time',
            field=models.PositiveSmallIntegerField(choices=[(1, '11:00am - 08:00pm'), (2, '12:00am - 08:00pm'), (3, '12:00am - 10:00pm'), (4, '01:00pm - 09:00pm'), (5, '03:00pm - 09:00pm'), (6, '03:00pm - 10:00pm')], null=True),
        ),
    ]
