# Generated by Django 4.1.2 on 2022-11-06 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0024_restaurant_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='status',
        ),
        migrations.AddField(
            model_name='menu',
            name='body',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurants.restaurant'),
        ),
    ]
