# Generated by Django 4.1.2 on 2022-11-06 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0025_alter_reservation_options_remove_menu_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='restaurant',
            new_name='restaurants',
        ),
    ]
