# Generated by Django 4.1.2 on 2022-11-10 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0030_alter_reservation_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='created_by',
        ),
        migrations.AddField(
            model_name='reservation',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
