# Generated by Django 4.1.2 on 2022-11-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0031_remove_reservation_created_by_reservation_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='approve',
            new_name='approved',
        ),
    ]
