# Generated by Django 4.1.2 on 2022-11-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0032_rename_approve_review_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='reserve',
        ),
    ]
