# Generated by Django 4.1.2 on 2022-11-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0033_remove_restaurant_rating_remove_restaurant_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
