# Generated by Django 4.1.2 on 2022-11-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0034_alter_restaurant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='body',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(max_length=3500, null=True),
        ),
    ]
