# Generated by Django 4.1.2 on 2022-10-17 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0006_remove_cuisine_likes_remove_cuisine_restaurants_and_more'),
        ('cuisines', '0002_menu_delete_cuisine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='restaurants',
            new_name='restaurant',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AddField(
            model_name='review',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_review', to='cuisines.menu'),
        ),
        migrations.AddField(
            model_name='review',
            name='restaurants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_review', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
