# Generated by Django 4.1.2 on 2022-10-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisines', '0003_rename_restaurants_menu_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
