# Generated by Django 4.1.2 on 2022-10-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_email_booking_first_name_booking_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='table_number',
            field=models.IntegerField(verbose_name=6),
        ),
    ]
