# Generated by Django 4.1.2 on 2022-10-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='table_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
