# Generated by Django 4.1.2 on 2022-10-28 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_alter_review_body'),
        ('bookings', '0007_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='restaurants.restaurant'),
        ),
    ]
