# Generated by Django 4.1.2 on 2022-10-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='restaurant',
            new_name='restaurants',
        ),
    ]
